### ISSUE TITLE
ADCIRCPY NOAA report

### ISSUE THREAD

**Issue by saeed-moghimi-noaa** [noaa-ocs-modeling/CoupledModelDriver#102] opened 2021-06-02 13:59 UTC

**Comment by zacharyburnettNOAA** [comment] 2021-06-02 14:07
duplicate of https://github.com/JaimeCalzadaNOAA/adcircpy/issues/50

**Comment by JaimeCalzadaNOAA** [comment] 2021-06-02 14:14
PR: https://github.com/JaimeCalzadaNOAA/adcircpy/pull/57

**Comment by saeed-moghimi-noaa** [comment] 2021-06-02 14:28
@JaimeCalzadaNOAA 
- wrap the comments and finalize
- cover pages
- Start communicating with Zizang 
- adobe test (accessibility)

**Closed** 2021-06-16 14:05 UTC
Labels: documentation, duplicate
